.SUFFIXES:
MAKEFLAGS += -r

# -----------------------------
# User-configurable variables
# -----------------------------
ORFS ?= ext/OpenROAD-flow-scripts
CELL_REPO ?= ext/asap7sc7p5t_28
VERILATOR_REPO ?= ext/verilator
TRACE2POWER_REPO ?= ext/trace2power

OPENROAD_BIN ?= $(ORFS)/tools/install/OpenROAD/bin
TRACE2POWER_TOP_SCOPE ?= tb.adder_
TRACE2POWER_POWER_SCOPE ?= '$(TRACE2POWER_TOP_SCOPE).core1'
TEST_DIR := $(PWD)/example_adder
VERILATOR_OUT := $(TEST_DIR)/out/Vtb
BASE_TCL := $(TEST_DIR)/base_output.tcl

RESULTS_DIR := $(ORFS)/flow/results/asap7/adder/base


# Verilator
export PATH := $(PATH):$(VERILATOR_REPO)/bin
# trace2power
export PATH := $(PATH):$(TRACE2POWER_REPO)/target/release
# OpenROAD
export PATH := $(PATH):$(OPENROAD_BIN)
# sta
export PATH := $(PATH):$(ORFS)/tools/OpenROAD/build/src/sta

export CELL_SOURCES := $(ORFS)/flow/platforms/asap7/verilog/stdcell
export LIB_DIR := $(ORFS)/flow/platforms/asap7/lib/NLDM/
export LEF_DIR := $(ORFS)/flow/platforms/asap7/lef
export VCD_FILE := $(TEST_DIR)/sim.vcd


# -----------------------------
# Top-level phony targets
# -----------------------------
.PHONY: all synthesis clean power_base \
    simulate power_full sta_full

all: synthesis simulate power_base sta

synthesis: $(TEST_DIR)/verilog/adder_core_synth.v
.PRECIOUS: $(TEST_DIR)/verilog/adder_core_synth.v
$(TEST_DIR)/verilog/adder_core_synth.v: $(TEST_DIR)/design/* $(TEST_DIR)/verilog/adder_core/*
	rm -rf $(ORFS)/flow/designs/asap7/adder/
	mkdir -p $(ORFS)/flow/designs/asap7/adder/
	cp $(TEST_DIR)/design/* $(ORFS)/flow/designs/asap7/adder/
	rm -rf $(ORFS)/flow/designs/src/adder/
	mkdir -p $(ORFS)/flow/designs/src/adder/
	cp $(TEST_DIR)/verilog/adder_core/* $(ORFS)/flow/designs/src/adder/
	cd $(ORFS) && make -C flow DESIGN_CONFIG=designs/asap7/adder/config.mk synth
	cp -v $(RESULTS_DIR)/1_2_yosys.v $(TEST_DIR)/verilog/adder_core_synth.v


# -----------------------------
# Build + run simulation
# -----------------------------
simulate: $(VCD_FILE)
.PRECIOUS: $(VCD_FILE)

$(VERILATOR_OUT): $(TEST_DIR)/verilog/adder_core_synth.v $(TEST_DIR)/post_synthesis.vc
	cd $(TEST_DIR) && \
	verilator --binary --build -f post_synthesis.vc \
		--trace-vcd \
		--timescale 1ns/10ps \
		-Wno-MULTIDRIVEN -Wno-WIDTHEXPAND -Wno-SPECIFYIGN -Wno-WIDTHTRUNC -Wno-fatal \
		-j $$(nproc)

$(VCD_FILE): $(VERILATOR_OUT)
	cd $(TEST_DIR) && ./out/Vtb +trace


# ========================================
# Power analysis
# ========================================

power_base: $(VCD_FILE)
	trace2power --clk-freq 200000000 \
		--limit-scope $(TRACE2POWER_TOP_SCOPE) \
		--limit-scope-power $(TRACE2POWER_POWER_SCOPE) \
		--input-ports-activity \
		--output $(BASE_TCL) $(VCD_FILE)
	cp -v $(BASE_TCL) $(RESULTS_DIR)/
	cp -v $(VCD_FILE) $(RESULTS_DIR)/

sta: power_base $(RESULTS_DIR) $(BASE_TCL)
	cd $(RESULTS_DIR) && openroad $(TEST_DIR)/openroad_commands || cat power_estimation.txt

power_full: $(VCD_FILE)
	trace2power --clk-freq 200000000 \
	    --limit-scope $(TRACE2POWER_TOP_SCOPE) \
	    --input-ports-activity \
	    --output $(BASE_TCL) $(VCD_FILE)
	cp -v $(BASE_TCL) $(RESULTS_DIR)/

sta_full: power_full $(RESULTS_DIR) $(BASE_TCL)
	cd $(RESULTS_DIR) && openroad $(TEST_DIR)/openroad_commands || cat power_estimation.txt

sta_instances:
	cd $(RESULTS_DIR) && openroad $(TEST_DIR)/openroad_commands_instances

clean:
	rm -vrf $(VERILATOR_OUT) $(TEST_DIR)/out $(VCD_FILE) $(BASE_TCL) $(GLITCH_DIR) $(TOTAL_DIR) $(TEST_DIR)/verilog/adder_core_synth.v $(RESULTS_DIR)

